title:              "PERPORMANCE 119"
tagline:            "프로그래매틱, Self-serve 광고로 똑똑하게 FLEX 하는 법"
email:              "sugar_crush@naver.com"
description:        "Data-driven｜Audience-oriented Planning｜Activation｜Optimization"
author:             "Joy"
baseurl:            "/"
url:                "https://performance119.com/"
locale:             "ko_KR"
thumbnail:          "/img/blog-thum.png"

# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  zoahye
linkedin_username:  dahye-jung-2a3188184

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate


# 블로그 disqus shortname
disqus:
  shortname: performance119
